### ISSUE TITLE
Tool-agnostic distinction between failed analysis and successful analysis without issues

### ISSUE THREAD

**Issue by gsalzer** [smartbugs/smartbugs#49]
Suppose the directory `/home/ethereum/tools/smartbugs/test` contains the two contracts `A.sol`:
```
contract A {
  function get(string _hash) constant returns (bool success) {
      success = true;
  }
}
```
and `B.sol`:
```
pragma solidity ^0.4.21;
contract A {
  function get(string _hash) public pure returns (bool success) {
      success = true;
  }
}
```
Then the analysis with the command

    python smartBugs.py --tool mythril --file ~/tools/smartbugs/test

will lead to a compilation error for `A.sol` but to a successful analysis for `B.sol` (without issues). This essential difference is not reflected in the respective `*.sarif` files, which are identical except for the contract name.

How can one distinguish these two situations without the need to analyze tool-specific output (like `result.log` or certain fields in `result.json`), which would require knowledge about how the tools report failures and issues?

**Comment by jff** [comment]
Thanks @gsalzer. We'll look at this in more detail.

@dindonero Should the SARIF be the same in this case?

**Comment by gsalzer** [comment]
At least for `result.json`, this problem is solved in branch `bytecode`. There are now fields `errors` and `success`. `errors` is a list of strings indicating errors, and success is a boolean which essentially is true if and only if `errors` is empty.

**Comment by jff** [comment]
This seems to have been solved in the `bytecode` branch, right @gsalzer ?

**Comment by gsalzer** [comment]
@jff Errors and fails of the tool itself will be reported by SB 2.0 (and by the code on the bytecode branch) in the parsed output. However, these errors and fails will still not be reflected in the sarif output. Should we include general fails and errors that are not tied to a particular code line in the sarif output?
